version: '3'

services:
  client:
    build:
      context: ./Sonata-Sage-Client/
    ports:
      - "5173:5173"
    volumes:
      - ./Sonata-Sage-Client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
  server:
    build:
      context: ./Sonata-Sage-Server/
    ports:
      - "8000:8000"
    volumes:
      - ./Sonata-Sage-Server/server:/app
    command: python manage.py runserver 0.0.0.0:8000
